### ISSUE TITLE
get build slide working on fall2024

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1702]
Here's what I see in my terminal when I try to build.
```
./build-slide -z bar-and-pie-charts     
make --no-print-directory -f lib/maker/Makefile.phase1
distribution/en-us/lessons updated
distribution/en-us/courses updated
lib/maker/collect-distribution-info.lua
make --no-print-directory -f lib/maker/Makefile.phase2
lib/maker/run-asciidoctor.sh
lib/maker/collect-specials.lua
lib/maker/do-postproc.lua
lib/maker/make-pathway-tocs.lua
objc[52902]: Class GNotificationCenterDelegate is implemented in both /opt/homebrew/Cellar/glib/2.76.2/lib/libgio-2.0.0.dylib (0x10e0f46b0) and /Users/flannery/Documents/Bootstrap/curriculum/node_modules/sharp/vendor/8.14.4/darwin-arm64v8/lib/libvips-cpp.42.dylib (0x113d99a40). One of the two will be used. Which one is undefined.
Slides failed for bar-and-pie-charts/zlides.mkd
Unable to generate slides: AssertionError [ERR_ASSERTION]: undefined == true
    at inlineTokenRules.bullet_list_open.inlineTokenRules.ordered_list_open (file:///Users/flannery/Documents/Bootstrap/curriculum/node_modules/md2googleslides/lib/parser/extract_slides.js:250:3)
    at processMarkdownToken (file:///Users/flannery/Documents/Bootstrap/curriculum/node_modules/md2googleslides/lib/parser/extract_slides.js:51:5)
    at file:///Users/flannery/Documents/Bootstrap/curriculum/node_modules/md2googleslides/lib/parser/extract_slides.js:62:5
    at Array.forEach (<anonymous>)
    at processTokens (file:///Users/flannery/Documents/Bootstrap/curriculum/node_modules/md2googleslides/lib/parser/extract_slides.js:57:10)
    at extractSlides (file:///Users/flannery/Documents/Bootstrap/curriculum/node_modules/md2googleslides/lib/parser/extract_slides.js:498:3)
    at SlideGenerator.generateFromMarkdown (file:///Users/flannery/Documents/Bootstrap/curriculum/node_modules/md2googleslides/lib/slide_generator.js:167:19)
    at generateSlides (file:///Users/flannery/Documents/Bootstrap/curriculum/node_modules/md2googleslides/bin/md2gslides.js:223:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}
flannery@Flannerys-MacBook-Air curriculum % 

```

Also the slides README on `fall2024` is out of date and I couldn't find the information I needed there.

**Comment by retabak** [comment]
here's what I get:

```

retabak@laptop:~/curriculum$ ./build-slide -z commutative-property
make --no-print-directory -f lib/maker/Makefile.phase1
Updating existing lesson distribution/en-us/lessons/commutative-property
Updating existing lesson distribution/en-us/lessons/codap-building
Updating existing lesson distribution/en-us/lessons/codap-dot-plots-bar-charts
Updating existing lesson distribution/en-us/lessons/codap-exploring
Updating existing lesson distribution/en-us/lessons/codap-filtering
distribution/en-us/lessons updated
Updating existing course distribution/en-us/courses/algebra-pyret
Updating existing course distribution/en-us/courses/algebra-wescheme
Updating existing course distribution/en-us/courses/data-science-codap
Updating existing course distribution/en-us/courses/data-science
Updating existing course distribution/en-us/courses/early-math
Updating existing course distribution/en-us/courses/hour-of-code
distribution/en-us/courses updated
lib/maker/collect-distribution-info.lua
make --no-print-directory -f lib/maker/Makefile.phase2
lib/maker/run-asciidoctor.sh
WARNING: Lesson plan distribution/en-us/lessons/commutative-property-wescheme/index.adoc: File distribution/en-us/lessons/commutative-property-wescheme/slides-wescheme.id not found

lib/maker/collect-specials.lua
lib/maker/do-postproc.lua
lib/maker/make-pathway-tocs.lua
Slides failed for commutative-property/zlides.mkd
Unable to generate slides: AssertionError [ERR_ASSERTION]: undefined == true
    at inlineTokenRules.bullet_list_open.inlineTokenRules.ordered_list_open (file:///home/retabak/curriculum/node_modules/md2googleslides/lib/parser/extract_slides.js:250:3)
    at processMarkdownToken (file:///home/retabak/curriculum/node_modules/md2googleslides/lib/parser/extract_slides.js:51:5)
    at file:///home/retabak/curriculum/node_modules/md2googleslides/lib/parser/extract_slides.js:62:5
    at Array.forEach (<anonymous>)
    at processTokens (file:///home/retabak/curriculum/node_modules/md2googleslides/lib/parser/extract_slides.js:57:10)
    at extractSlides (file:///home/retabak/curriculum/node_modules/md2googleslides/lib/parser/extract_slides.js:498:3)
    at SlideGenerator.generateFromMarkdown (file:///home/retabak/curriculum/node_modules/md2googleslides/lib/slide_generator.js:167:19)
    at generateSlides (file:///home/retabak/curriculum/node_modules/md2googleslides/bin/md2gslides.js:223:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}
```

**Comment by retabak** [comment]
that's what I was getting as well.

**Comment by schanzer** [comment]
@ds26gte I think I've found the issue, but I don't know enough about `slides-preproc.rkt` to fix it. The following will consistently generate the error (snagged from bar-and-pie-charts):

```
== Grouping by Value @duration{25 minutes}

=== Launch

[0 or more lines of adoc]

@slidebreak
@QandA{
@Q{How do the count table and bar chart you just made compare?}
@A{The height of each bar matches the count of each species.}
@Q{How does this pie chart compare to the bar chart you just made?}
@A{The wedges show percentages, whereas the bar chart was labeled with the count. We could figure out how many animals were in the sample from the bar chart. With the pie chart we see how the categories compare to each other, but we have no way of knowing how many animals each wedge represents.}
}
```

The issue is that `@slidebreak` should start a new slide and inherit the title bar from the precious heading title (in this case, "Grouping by Value"). But the generated `.mkd` file looks like this (benign newlines removed for readability):
```
{layout="Launch"}
# Grouping by Value 

---
* How do the count table and bar chart you just made compare?
* How does this pie chart compare to the bar chart you just made?

<!--
* How do the count table and bar chart you just made compare?
  -  The height of each bar matches the count of each species.
* How does this pie chart compare to the bar chart you just made?
  -  The wedges show percentages, whereas the bar chart was labeled with the count. We could figure out how many animals were in the sample from the bar chart. With the pie chart we see how the categories compare to each other, but we have no way of knowing how many animals each wedge represents.
-->
```

Notice that the `@QandA` resides on a slide with no title! That's what breaks the invariant in md2googleslides

**Comment by schanzer** [comment]
Confirming that Flannery's workflow now builds with no problems!
