### ISSUE TITLE
Slide build error - nested lists

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1769]
This is from the Contracts lesson. While I see lots of kinds of nested lists, I’m not seeing us switch from one kind to another within a list (although I know this has happened elsewhere)

```
Unable to generate slides: Error: Nested lists must match parent style
  at inlineTokenRules.bullet_list_open.inlineTokenRules.ordered_list_open (file:///Users/flannery/Documents/Bootstrap/curriculum/node_modules/md2googleslides/lib/parser/extract_slides.js:252:13)
  at processMarkdownToken (file:///Users/flannery/Documents/Bootstrap/curriculum/node_modules/md2googleslides/lib/parser/extract_slides.js:50:5)
  at file:///Users/flannery/Documents/Bootstrap/curriculum/node_modules/md2googleslides/lib/parser/extract_slides.js:60:5
  at Array.forEach (<anonymous>)
  at processTokens (file:///Users/flannery/Documents/Bootstrap/curriculum/node_modules/md2googleslides/lib/parser/extract_slides.js:56:10)
  at fullTokenRules.html_block (file:///Users/flannery/Documents/Bootstrap/curriculum/node_modules/md2googleslides/lib/parser/extract_slides.js:331:3)
  at processMarkdownToken (file:///Users/flannery/Documents/Bootstrap/curriculum/node_modules/md2googleslides/lib/parser/extract_slides.js:50:5)
  at file:///Users/flannery/Documents/Bootstrap/curriculum/node_modules/md2googleslides/lib/parser/extract_slides.js:60:5
  at Array.forEach (<anonymous>)
  at processTokens (file:///Users/flannery/Documents/Bootstrap/curriculum/node_modules/md2googleslides/lib/parser/extract_slides.js:56:10)
  at extractSlides (file:///Users/flannery/Documents/Bootstrap/curriculum/node_modules/md2googleslides/lib/parser/extract_slides.js:493:3)
  at SlideGenerator.generateFromMarkdown (file:///Users/flannery/Documents/Bootstrap/curriculum/node_modules/md2googleslides/lib/slide_generator.js:167:19)
  at generateSlides (file:///Users/flannery/Documents/Bootstrap/curriculum/node_modules/md2googleslides/bin/md2gslides.js:226:25)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by schanzer** [comment]
Fixed!
