### ISSUE TITLE
Function Notation Slides won't build

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1918]
I've looked and looked, but I can't find the nested list that's being objected to. I'm guessing the error message is actually objecting to something else that's breaking a list somehow?

```
Slides failed for function-notation/slides.mkd
Unable to generate slides: Error: Nested lists must match parent style
  at inlineTokenRules.bullet_list_open.inlineTokenRules.ordered_list_open (file:///Users/flannery/Documents/Bootstrap/curriculum/node_modules/md2googleslides/lib/parser/extract_slides.js:260:13)
  at processMarkdownToken (file:///Users/flannery/Documents/Bootstrap/curriculum/node_modules/md2googleslides/lib/parser/extract_slides.js:50:5)
  at file:///Users/flannery/Documents/Bootstrap/curriculum/node_modules/md2googleslides/lib/parser/extract_slides.js:60:5
  at Array.forEach (<anonymous>)
  at processTokens (file:///Users/flannery/Documents/Bootstrap/curriculum/node_modules/md2googleslides/lib/parser/extract_slides.js:56:10)
  at fullTokenRules.html_block (file:///Users/flannery/Documents/Bootstrap/curriculum/node_modules/md2googleslides/lib/parser/extract_slides.js:339:3)
  at processMarkdownToken (file:///Users/flannery/Documents/Bootstrap/curriculum/node_modules/md2googleslides/lib/parser/extract_slides.js:50:5)
  at file:///Users/flannery/Documents/Bootstrap/curriculum/node_modules/md2googleslides/lib/parser/extract_slides.js:60:5
  at Array.forEach (<anonymous>)
  at processTokens (file:///Users/flannery/Documents/Bootstrap/curriculum/node_modules/md2googleslides/lib/parser/extract_slides.js:56:10)
  at extractSlides (file:///Users/flannery/Documents/Bootstrap/curriculum/node_modules/md2googleslides/lib/parser/extract_slides.js:501:3)
  at SlideGenerator.generateFromMarkdown (file:///Users/flannery/Documents/Bootstrap/curriculum/node_modules/md2googleslides/lib/slide_generator.js:167:19)
  at generateSlides (file:///Users/flannery/Documents/Bootstrap/curriculum/node_modules/md2googleslides/bin/md2gslides.js:226:25)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by schanzer** [comment]
@ds26gte this is the same issue we've seen before, and the fix is the same: list items that start with a numeric character cause a list collision, because markdown thinks the author has suddenly switched from bullet lists to numbered lists. If we insert a [zero width space](https://unicode-explorer.com/c/200B) at the start of every list bullet, we can prevent this from ever happening.

I've pushed a fix that inserts the character at the beginning of @Q and @A entries, but we should do this for _any_ list item at all. That will probably need some lua regexp magic from you, as I'm still learning...

**Comment by ds26gte** [comment]
This slide builds ok now, presumably because of a re-write. Could you give me a slide fragment where this triggers the failure?
