### ISSUE TITLE
Unforced builds do not build workbook PDFs

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#721]
1. `./build-pathway -f --book data-science`
2. Rejoice in the glory of the PDFs!
3. Open the `pages` folder of any lesson in the DS pathway, and delete one of the PDFs
4. `./build-pathway --book data-science`  <-- note the unforced nature of the build!

EXPECTED: the build system regenerates the PDF
ACTUAL:
```
Error: ENOENT: no such file or directory, open '/Users/schanzer/Documents/Bootstrap/Development/curriculum/distribution/en-us/courses/data-science/../../lessons/displaying-categorical-data/pages/bar-chart-notice.pdf'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at makeWorkbook (/Users/schanzer/Documents/Bootstrap/Development/curriculum/distribution/en-us/lib/makeWorkbook.js:37:22)
    at async makeAllWorkbooks (/Users/schanzer/Documents/Bootstrap/Development/curriculum/distribution/en-us/lib/makeWorkbook.js:91:3) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/schanzer/Documents/Bootstrap/Development/curriculum/distribution/en-us/courses/data-science/../../lessons/displaying-categorical-data/pages/bar-chart-notice.pdf'
}
```

**Comment by schanzer** [comment]
Turns out this was related to some corruption in the build script! Fixed by 0f895e8d0f6a2ab541618f976ec4535716f9441e
